apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-uat
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sharathsl/argocd_deploy.git
    targetRevision: uat
    path: uat
  destination:
    server: https://kubernetes.default.svc
    namespace: uat

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
