apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-uat
  namespace: uat
spec:
  selector:
    matchLabels:
      app: nginx-uat
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-uat
    spec:
      containers:
      - name: nginx-uat
        image: nginx:1.24
        ports:
        - containerPort: 80
