apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  namespace: dev
spec:
  selector:
    matchLabels:
      app: nginx-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
      - name: nginx-dev
        image: nginx:1.25
        ports:
        - containerPort: 80
  