apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: app
spec:
  selector:
    matchLabels:
      app: petclinic-app
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-app
        image: sharath2787/petclinic:21
        ports:
        - containerPort: 8080
